esphome:
  name: co2-sensor1
  friendly_name: CO2-sensor1
  platformio_options:
    board_build.f_cpu: 80000000L

  on_boot:              
    - priority: 400
      then:
        - component.update: battery_voltage
        - delay: 200ms
        - if:
            condition:
              lambda: 'return !id(low_batt_mode);'
            then:
              - delay: 100ms
              - component.update: scd41
            else:  
              - script.execute: finalize_measurement

    - priority: 200
      then:
        - if:
            condition:
              lambda: 'return id(low_batt_mode);'
            then:
              - wifi.disable

    - priority: -100
      then:
        # Pokud proměnná ještě neexistuje (po restartu)
        - if:
            condition:
              lambda: 'return isnan(id(wakecounter));'
            then:
              - lambda: |-
                  id(wakecounter) = 0;
                  ESP_LOGI("main", "Wakecounter initialized to 0 (fresh boot)");

        # Podmínky pro připojení WiFi
        - if:
            condition:
              - lambda: 'return id(wakecounter) == 0 &&  !id(low_batt_mode);'  # po restartu a po resetu wakecouteru
            then:
              - logger.log: "WiFi will be enabled this cycle"
              - wifi.enable:
              - wait_until:
                  condition:
                    wifi.connected:
                  timeout: 15s
              - logger.log: "WiFi connected!"
              - lambda: 'if (id(wakecounter) == 3) id(wakecounter) = 0;'
            else:
              - logger.log: "Skipping WiFi this cycle"
              - wifi.disable:
        # Zvýší čítač (cyklus každých 5 min)
        - lambda: |-
            id(wakecounter)++;
            if (id(wakecounter) >= 3) id(wakecounter) = 0;
            ESP_LOGI("main", "Wakecounter = %d", id(wakecounter));

esp32:
  board: esp32dev
  framework:
    type: arduino

logger:

api:
  encryption:
    key: !secret api_encryption_key
  on_client_connected:
    then:
      - delay: 300ms 
      - lambda: |-
          if (id(ha_ota_mode).state) {
            ESP_LOGI("ota", "OTA mode active → sleep DISABLED");
            id(allow_sleep) = false;
          } else {
            ESP_LOGI("ota", "Normal mode → sleep allowed");
            id(allow_sleep) = true;
          }
      - if:
          condition:
            binary_sensor.is_on: ha_ota_mode
          then:
            - script.execute: ota_timeout
          else:
            - script.stop: ota_timeout


ota:
  - platform: esphome
    password: "4210c560b941485b08fda92d9df21235"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  power_save_mode: light
  fast_connect: true
  reboot_timeout: 0s
  manual_ip:
    static_ip: 192.168.10.28
    gateway: 192.168.10.1
    subnet: 255.255.255.0
  on_connect:
    then:
      - if:
          condition:
            and:
              - binary_sensor.is_on: ha_calibrate_request
              - lambda: 'return !id(calibration_done_this_boot);'
          then:
            - logger.log: "HA requested CO2 calibration"
            - scd4x.perform_forced_calibration:
                value: 419
            - lambda: 'id(calibration_done_this_boot) = true;'
            - delay: 2s
            - homeassistant.service:
                service: input_boolean.turn_off
                data:
                  entity_id: input_boolean.co2_sensor1_manual_cal

globals:
  - id: wakecounter
    type: int
    restore_value: yes
    initial_value: '0'

  - id: measurement_done
    type: bool
    restore_value: no
    initial_value: 'false'

  - id: co2_cached
    type: int
    restore_value: no
    initial_value: '0'

  - id: temp_cached
    type: float
    restore_value: no
    initial_value: '0.0'

  - id: hum_cached
    type: float
    restore_value: no
    initial_value: '0.0'

  - id: scd41_valid
    type: bool
    restore_value: yes
    initial_value: 'false'

  - id: low_batt_mode
    type: bool
    restore_value: no
    initial_value: 'false'

  - id: last_batt_voltage
    type: float
    restore_value: yes
    initial_value: '0.0'

  - id: charging_detected
    type: bool
    restore_value: yes
    initial_value: 'false'

  - id: allow_sleep
    type: bool
    initial_value: 'true'
    restore_value: yes

  - id: calibration_done_this_boot
    type: bool
    restore_value: no
    initial_value: 'false'

binary_sensor:
  - platform: homeassistant
    id: ha_ota_mode
    entity_id: input_boolean.co2_sensor1_ota_mode
    on_state:
      then:
        - lambda: |-
            id(allow_sleep) = !x;  // OTA ON → zákaz sleep

  - platform: homeassistant
    id: ha_calibrate_request
    entity_id: input_boolean.co2_sensor1_manual_cal

i2c:
  sda: 0
  scl: 4

spi:
  clk_pin: 18
  mosi_pin: 23

sensor:
  - platform: scd4x
    id: scd41
    address: 0x62
    measurement_mode: single_shot
    update_interval: 7s
    altitude_compensation: 567m
    temperature_offset: 0.0
    automatic_self_calibration: false
    co2:
      id: co2
      name: "CO2"
      accuracy_decimals: 0
      on_value:
        then:
          - lambda: |-
              if (!id(measurement_done)) {
                if (x > 300 && x < 10000) {
                  id(co2_cached) = (int)x;
                  id(scd41_valid) = true;
                }
              }
    temperature:
      id: temperature
      name: "Teplota"
      accuracy_decimals: 1
      on_value:
        then:
          - lambda: |-
              if (!id(measurement_done)) {
                id(temp_cached) = x;
              }
    humidity:
      id: humidity
      name: "Vlhkost"
      accuracy_decimals: 0
      on_value:
        then:
          - lambda: |-
              id(hum_cached) = x;
          - script.execute: finalize_measurement

  - platform: adc
    pin: 35
    attenuation: auto
    name: "VBatt"
    id: battery_voltage
    update_interval: 2s
    filters:
      - multiply: 1.985
      - median:
          window_size: 3
          send_every: 3
          send_first_at: 3
    on_value:
      then:
        - lambda: |-
            if (x < 3.2) {
              id(low_batt_mode) = true;
            } else if (x > 3.4) {
              id(low_batt_mode) = false;
            }

            float v = x;

            if (id(last_batt_voltage) > 0.1) {
              float delta = v - x;

              if (delta > 0.025) {
                id(charging_detected) = true;
              } else if (delta < 0.01) {
                id(charging_detected) = false;
              }
            }
            id(last_batt_voltage) = v;

  - platform: wifi_signal
    id: wifi_sig
    name: "WiFi Signal"
    update_interval: 5s

button:
  - platform: template
    name: "CO2 manual calibration (only in fresh air for at least 20min)"
    entity_category: "config"
    on_press:
      then:
      - scd4x.perform_forced_calibration:
          value: 419

script:
  - id: finalize_measurement
    mode: single
    then:
      - lambda: |-
          id(measurement_done) = true;
      - component.update: epaper
      - delay: 2.5s
      #- deep_sleep.enter: deep_sleep_10min
      - if:
          condition:
            lambda: 'return id(low_batt_mode);'
          then:
            - deep_sleep.enter:
                id: sleep_ctrl
                sleep_duration: 15min
          else:
            - if:
                condition:
                  lambda: 'return id(allow_sleep);'
                then:
                  - deep_sleep.enter:
                      id: sleep_ctrl
                      sleep_duration: 5min
                else:
                  - logger.log: "Sleep blocked (OTA mode)"

  - id: ota_timeout
    mode: restart
    then:
      - logger.log: "OTA timeout started (15 min)"
      - delay: 15min
      - logger.log: "OTA timeout expired → enabling sleep"
      - homeassistant.service:
          service: input_boolean.turn_off
          data:
            entity_id: input_boolean.co2_sensor1_ota_mode
      - lambda: |-
          id(allow_sleep) = true;


font:
  - file: "fonts/Play-Bold.ttf"
    id: font_large
    size: 42

  - file: "fonts/Play-Bold.ttf"
    id: font_medium2
    size: 26

  - file: "fonts/Play-Bold.ttf"
    id: font_medium
    size: 22

  - file: "fonts/Play-Bold.ttf"
    id: font_small
    size: 14

  - file: 'fonts/materialdesignicons-webfont.ttf'
    id: font_mdi_large
    size: 42
    glyphs: &mdi-weather-glyphs
      - "\U000F07E4" # mdi-co2-molecule
      - "\U000F0026" # mdi-alert
      - "\U000F002A" # mdi-alert-outline
      - "\U000F17E9" # battery-remove-outline
      - "\U000F089C" # battery-charging-10

  - file: 'fonts/materialdesignicons-webfont.ttf'
    id: font_mdi_medium
    size: 26
    glyphs: 
      - "\U000F050F" # mdi-thermometer
      - "\U000F0E0A" # mdi-water-outline
      
  - file: 'fonts/materialdesignicons-webfont.ttf'
    id: font_mdi_small
    size: 14
    glyphs: 
      - "\U000F092E" # mdi-wifi-strength-off-outline
      - "\U000F092F" # mdi-wifi-strength-outline
      - "\U000F091F" # mdi-wifi-strength-1
      - "\U000F0922" # mdi-wifi-strength-2
      - "\U000F0925" # mdi-wifi-strength-3
      - "\U000F0928" # mdi-wifi-strength-4
      - "\U000F007C" # mdi-battery-low
      - "\U000F0080" # mdi-battery-medium
      - "\U000F0079" # mdi-battery-high
      - "\U000F10CD" # mdi-battery-alert-variant-outline
      - "\U000F0026" # mdi-alert
      - "\U000F002A" # mdi-alert-outline
      - "\U000F089C" # battery-charging-10
    
display:
  - platform: waveshare_epaper
    id: epaper
    cs_pin: 5
    dc_pin: 17
    reset_pin: 16
    busy_pin: 34
    model: 2.13inv3
    rotation: 270
    update_interval: never
    lambda: |-

      const auto WHITE   = Color(0,   0,   0,   0);
      const auto RED     = Color(255, 0, 0, 0);
      const auto BLACK   = Color(255, 255, 255, 0);
      it.fill(WHITE);

      // ---- Vybita baterie ----
      if (id(low_batt_mode)) {
        if (id(charging_detected)) {
          // zobraz charging ikonu
          it.printf(100, 50, id(font_mdi_large), BLACK, "\U000F089C");  // Charging ikona
        } else {
          // zobraz low battery ikonu
          it.printf(100, 50, id(font_mdi_large), BLACK, "\U000F17E9");  // LOW BATT ikona
        }
        return;
      }
      // ---- Vybita baterie - Konec ----


      // --- Horni stavovy radek ---
      float batt = id(battery_voltage).state;
      float wifi = id(wifi_sig).has_state() ? id(wifi_sig).state : NAN;

      int batt_y = 2;
      int batt_x = 140;
      
      // --- Wi-Fi ---
      if (!isnan(wifi)) {
        if (wifi >= -55){
          it.printf(10, batt_y, id(font_mdi_small), BLACK, "\U000F0928"); // wifi high
        }
        else if (wifi >= -67){
          it.printf(10, batt_y, id(font_mdi_small), BLACK, "\U000F0925"); // wifi med
        }
        else if (wifi >= -75){
          it.printf(10, batt_y, id(font_mdi_small), BLACK, "\U000F091F"); // wifi low
        }
        else {
          it.printf(10, batt_y, id(font_mdi_small), BLACK, "\U000F092F"); // wifi very low
        }

        it.printf(25, batt_y - 1, id(font_small), BLACK, "%.0f dBm", wifi);
      }

      if (!id(allow_sleep)) {
        it.printf(100, batt_y - 2, id(font_small), BLACK, "OTA");  // OTA napis
      }

      // --- Baterie ---
      if (!isnan(batt)) {
        float percent = (batt - 3.2) / (4.1 - 3.2) * 100.0;
        if (percent > 100) percent = 100;
        if (percent < 0) percent = 0;

        if (id(charging_detected)) {
          // pokud nabijime zobraz charging ikonu
          it.printf(100, 50, id(font_mdi_small), BLACK, "\U000F089C");  // Charging ikona
        }
        else{
          // pokud bezime na baterii, zobraz stav
          if (percent >= 75){
            it.printf(batt_x, batt_y, id(font_mdi_small), BLACK, "\U000F0079"); // batt high
          }
          else if (percent >= 50){
            it.printf(batt_x, batt_y, id(font_mdi_small), BLACK, "\U000F0080"); // batt med
          }
          else if (percent >= 25){
            it.printf(batt_x, batt_y, id(font_mdi_small), BLACK, "\U000F007C"); // batt low
          }
          else {
            it.printf(batt_x, batt_y, id(font_mdi_small), BLACK, "\U000F10CD"); // batt critical
          }
        }
        it.printf(batt_x + 15, batt_y - 2, id(font_small), BLACK, "%.2fV (%.0f%%)", batt, percent);
      }

      // --- horizontalni cara - horni stavovy radek --------
      it.filled_rectangle(10, 20, 230, 2); 

      // --- CO2 hlavní hodnota ---
      int co2_x = 5;
      int co2_y = 25;

      if (id(co2_cached) > 0) {
        it.printf(co2_x, co2_y + 10, id(font_mdi_large), BLACK, "\U000F07E4");  // CO2 ikona
        it.printf(co2_x + 40, co2_y, id(font_large), BLACK, TextAlign::TOP_LEFT, "%4d", id(co2_cached));
        it.printf(co2_x + 140, co2_y + 43, id(font_medium), BLACK, TextAlign::BOTTOM_LEFT, "ppm");
      
        // varovny symbol pro vysoke CO2
        if (id(co2_cached) > 1500) {
          it.printf(co2_x + 190, co2_y + 5, id(font_mdi_large), BLACK, "\U000F0026");  // CO2 Alert2
        }
        else if (id(co2_cached) > 1200) {
          it.printf(co2_x + 190, co2_y + 5, id(font_mdi_large), BLACK, "\U000F002A");  // CO2 Alert1
        }      
        else {
          it.filled_rectangle(co2_x + 190, co2_y + 5, 30, 30, WHITE);  // Smazat CO2 Alert
        }
      }

      int temp_y = 83;
      if (!isnan(id(temp_cached))) {
        it.printf(0, temp_y + 3, id(font_mdi_medium), BLACK, "\U000F050F");  // teploměr
        it.printf(30, temp_y, id(font_medium2), BLACK, "%.1f °C", id(temp_cached));
      }
      
      int hum_y = temp_y;
      if (!isnan(id(hum_cached))) {
        it.printf(145, hum_y + 3, id(font_mdi_medium), BLACK, "\U000F0E0A");  // kapka
        it.printf(175, hum_y, id(font_medium2), BLACK, "%.0f %%", id(hum_cached));
      }

          
#deep_sleep:
 # id: deep_sleep_10min
 # sleep_duration: 5min

deep_sleep:
  id: sleep_ctrl
